Do not attempt to get datestamp
- This is causing an error with the version of ruby I'm using and my feed:
    - ruby 1.8.7
    - feed: http://codrspace.com/durden/feed
- Error is:
    "#<NoMethodError: undefined method `utc' for nil:NilClass>"